test_string= "kemi"
print("kemi")
print(test_string.capitalize())
print(test_string.upper())
print(test_string.casefold())
print(test_string.count("kemi"))
print(test_string.encode())
print(test_string.endswith("i"))
print(test_string.find("e"))
print(test_string.expandtabs())
print(test_string.format())
print(test_string.isdigit())
print(test_string.format())
print(test_string.format_map())
print(test_string.index())
print(test_string.isalnum())
print(test_string.isalpha())
print(test_string.islower())
print(test_string.replace())
print(test_string.isupper()
print(test_string.partition())
print(test_string.lstrip())
print(test_string.maketrans())
print(test_string.isprintable())
print(test_string.isnumeric()
print(test_string.isascii())
print(test_string.isdigit())
print(test_string.rfind())
print(test_string.rjust())
print(test_string.rpartition())
print(test_string.rindex())
print(test_string.rstrip())
print(test_string.rsplit())
print(test_string.title()
print(test_string.swapcase())
print(test_string.startswith())
print(test_string.splitlines())
print(test_string.translate())
print(test_string.zfill())



